# dbt_project.yml
name: 'financial_model'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_financial_model:
    intermediate:
      +materialized: table
      int_net_revenues:
        +materialized: incremental
        +unique_key: 'transaction_date'
        +cluster_by: ['transaction_date', 'customer_id']
    marts:
      +materialized: table
      mrt_customer_revenues:
        +materialized: incremental
        +unique_key: ['customer_id', 'revenue_month']
        +cluster_by: ['revenue_month', 'customer_segment']
        +partition_by: {
          'field': 'revenue_month',
          'data_type': 'date',
          'granularity': 'month'
        }